### ISSUE TITLE
Tab navigation

### ISSUE THREAD

**Issue by johanehinger** [kledd-team/kledd#8]
Create a screen with a [BottomNavigationBar](https://api.flutter.dev/flutter/material/BottomNavigationBar-class.html) named **tab_screen**.
Also create widgets **explore_tab**, **profile_tab** and **new_item_tab** to navigate between. Put these widgets in lib/widgets/tabs.
![nedladdning](https://user-images.githubusercontent.com/65904251/89489631-39f5a200-d7ab-11ea-8046-342022ef0c2d.png)

**Comment by Kal-Elx** [comment]
Consider naming this feed_screen or items_screen instead.

**Comment by Kal-Elx** [comment]
I chose to have the tabs as screens with there individual Scaffolds.

**Comment by Kal-Elx** [comment]
Closed in #17
